version: "3.9"

volumes:
  app_media:
  app_static:
  pg_data:
x-main: &main
  image: blog_project
  restart: always
  build:
    context: .
    dockerfile: compose/Dockerfile
  volumes:
    - app_static:/app/static_root
    - app_media:/app/media
  env_file:
    - ./docker.env
  depends_on:
    - redis
services:
  app:
    <<: *main
  worker:
    <<: *main
    command: 'celery -A core worker -l info'
  beat:
    <<: *main
    command: celery -A core beat -l INFO --scheduler django_celery_beat.schedulers:DatabaseScheduler
  flower:
    <<: *main
    command: celery -A core flower --address=0.0.0.0 --port=5566
    ports:
      - "5566:5566"
  nginx:
    image: nginx:1.21.4-alpine
    restart: on-failure
    volumes:
      - app_static:/static:ro
      - app_media:/media:ro
      - ./compose/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    depends_on:
      - app
  db:
    image: postgres:14-alpine
    restart: on-failure
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - ./docker.env
  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"
