version: "3.9"

volumes:
  app_media:
  app_static:
  pg_data:

services:
  app:
    image: blog_project
    restart: always
    build:
      context: .
      dockerfile: compose/Dockerfile
    volumes:
      - app_static:/app/static_root
      - app_media:/app/media
    env_file:
      - ./docker.env
  nginx:
    image: nginx:1.21.4-alpine
    restart: on-failure
    volumes:
      - app_static:/static:ro
      - app_media:/media:ro
      - ./compose/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    depends_on:
      - app
  db:
    image: postgres:14-alpine
    restart: on-failure
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - ./docker.env
